"use client";

import React, { FormEvent, KeyboardEvent, useCallback, useEffect, useRef, useState } from "react";
import { Activity, ArrowLeft, ArrowRight, Check, Clipboard, Download, Edit2, List, LockKeyhole, MessageCircle, Pause, Plus, RefreshCw, Search, Send, Settings2, ShieldAlert, Trash2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import Link from "next/link";
import { DEFAULT_SETTINGS, DEFAULT_VAULT, type ChatMessage, type Conversation, type LocalSettings, type Memory, type VaultData } from "@/lib/chat/types";
import { permanentlyDeleteVault, readVault, unlockVault, vaultExists as hasEncryptedVault, writeVault } from "@/lib/storage/encrypted-vault";
import { getVaultSessionKey, lockVaultSession, setVaultSessionKey, vaultLockEvent } from "@/lib/storage/vault-session";

const SETTINGS_KEY = "mindspace.local-settings.v1";
type Model = { name: string; size: number | null };
function readSettings(): LocalSettings {
  try { const parsed = JSON.parse(localStorage.getItem(SETTINGS_KEY) ?? "null") as Partial<LocalSettings> | null; return { ...DEFAULT_SETTINGS, ...parsed }; } catch { return DEFAULT_SETTINGS; }
}
async function checkModels(endpoint: string) {
  const response = await fetch("/api/ollama/models", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ endpoint }) });
  const result = await response.json() as { connected?: boolean; models?: Model[]; error?: string };
  if (!response.ok || !result.connected) throw new Error(result.error ?? "Ollama is unavailable.");
  return result.models ?? [];
}
function id() { return crypto.randomUUID(); }
function fmtSize(size: number | null) { return size ? `${(size / 1_000_000_000).toFixed(size > 10_000_000_000 ? 0 : 1)} GB` : "Installed"; }
function localTime(value: string) { try { return new Date(value).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); } catch { return ""; } }

export function LocalChat() {
  const [key, setKey] = useState<CryptoKey | null>(null); const [vault, setVault] = useState<VaultData>(DEFAULT_VAULT); const vaultRef = useRef(vault); const [loadingVault, setLoadingVault] = useState(true); const [vaultReady, setVaultReady] = useState(false); const [passphrase, setPassphrase] = useState(""); const [vaultExists, setVaultExists] = useState<boolean | null>(null); const [unlockError, setUnlockError] = useState(""); const [settings, setSettings] = useState<LocalSettings>(DEFAULT_SETTINGS); const [models, setModels] = useState<Model[]>([]); const [connected, setConnected] = useState(false); const [connectionError, setConnectionError] = useState(""); const [selected, setSelected] = useState(""); const [activeId, setActiveId] = useState(""); const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [search, setSearch] = useState(""); const [searchOpen, setSearchOpen] = useState(false); const [showHistory, setShowHistory] = useState(false); const [memoryOpen, setMemoryOpen] = useState(false); const [memoryDraft, setMemoryDraft] = useState(""); const [editingMemory, setEditingMemory] = useState(""); const [notice, setNotice] = useState("");
  const abortRef = useRef<AbortController | null>(null); const inputRef = useRef<HTMLTextAreaElement>(null); const saveTimer = useRef<ReturnType<typeof setInterval> | null>(null); const scrollRef = useRef<HTMLDivElement>(null);
  const active = vault.conversations.find((conversation) => conversation.id === activeId) ?? vault.conversations[0];
  const activeMessages = active?.messages ?? [];
  const setVaultSafe = useCallback((next: VaultData) => { vaultRef.current = next; setVault(next); }, []);
  const persist = useCallback(async (next: VaultData) => { vaultRef.current = next; setVault(next); if (key) await writeVault(key, next); }, [key]);

  useEffect(() => { setSettings(readSettings()); const sessionKey = getVaultSessionKey(); if (sessionKey) setKey(sessionKey); void hasEncryptedVault().then((exists) => setVaultExists(exists)).catch(() => { setUnlockError("Encrypted browser storage is unavailable. Use a current browser with IndexedDB enabled."); setVaultExists(false); }).finally(() => setLoadingVault(false)); }, []);
  useEffect(() => { if (!key) { setVaultReady(false); return; } let alive = true; setVaultReady(false); void readVault(key).then((data) => { if (alive) { setVaultSafe(data); setActiveId((current) => current || data.conversations[0]?.id || ""); setVaultReady(true); } }).catch((error: Error) => { if (alive) { setUnlockError(error.message); setKey(null); setVaultReady(false); } }); return () => { alive = false; }; }, [key, setVaultSafe]);
  useEffect(() => { if (!key) return; let alive = true; void checkModels(settings.endpoint).then((list) => { if (!alive) return; setModels(list); setConnected(true); setConnectionError(""); setSelected((current) => list.some((model) => model.name === current) ? current : settings.model && list.some((model) => model.name === settings.model) ? settings.model : list[0]?.name ?? ""); }).catch((error: Error) => { if (alive) { setModels([]); setConnected(false); setConnectionError(error.message); } }); return () => { alive = false; }; }, [key, settings.endpoint, settings.model]);
  const activeLastContent = activeMessages.at(-1)?.content;
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); }, [activeMessages.length, activeLastContent]);
  useEffect(() => { const onKey = (e: globalThis.KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "n") { e.preventDefault(); void newConversation(); } if (e.key === "Escape" && abortRef.current) stop(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); });
  useEffect(() => () => { abortRef.current?.abort(); if (saveTimer.current) clearInterval(saveTimer.current); }, []);

  useEffect(() => { const clear = () => { abortRef.current?.abort(); setKey(null); setVaultReady(false); }; window.addEventListener(vaultLockEvent(), clear); return () => window.removeEventListener(vaultLockEvent(), clear); }, []);
  async function unlock(e: FormEvent) { e.preventDefault(); setUnlockError(""); setLoadingVault(true); try { const result = await unlockVault(passphrase); setVaultSessionKey(result.key); setKey(result.key); setPassphrase(""); setVaultExists(true); setNotice(result.isNew ? "Encrypted vault created. Keep your passphrase safe; it cannot be reset." : "Vault unlocked."); } catch (error) { setUnlockError((error as Error).message); } finally { setLoadingVault(false); } }
  async function newConversation() { const now = new Date().toISOString(); const conversation = { id: id(), title: "New conversation", createdAt: now, updatedAt: now, messages: [] }; try { await persist({ ...vaultRef.current, conversations: [conversation, ...vaultRef.current.conversations].slice(0, 100) }); setActiveId(conversation.id); setDraft(""); setMemoryOpen(false); inputRef.current?.focus(); } catch { setNotice("Could not save the conversation. Check available browser storage."); } }
  async function removeConversation(conversation: Conversation) { if (!window.confirm(`Permanently delete “${conversation.title}” from this device?`)) return; const next = { ...vaultRef.current, conversations: vaultRef.current.conversations.filter((item) => item.id !== conversation.id) }; try { await persist(next); if (activeId === conversation.id) setActiveId(next.conversations[0]?.id ?? ""); } catch { setNotice("Could not delete this conversation."); } }
  async function renameConversation(conversation: Conversation) { const title = window.prompt("Rename conversation", conversation.title); if (!title?.trim()) return; try { await persist({ ...vaultRef.current, conversations: vaultRef.current.conversations.map((item) => item.id === conversation.id ? { ...item, title: title.trim().slice(0, 72) } : item) }); } catch { setNotice("Could not rename this conversation."); } }
  async function clearConversation(conversation: Conversation) { if (!window.confirm("Delete every message in this conversation? This cannot be undone.")) return; try { await persist({ ...vaultRef.current, conversations: vaultRef.current.conversations.map((item) => item.id === conversation.id ? { ...item, messages: [], title: "New conversation", updatedAt: new Date().toISOString() } : item) }); } catch { setNotice("Could not clear this conversation."); } }
  function stop() { abortRef.current?.abort(); abortRef.current = null; setBusy(false); if (saveTimer.current) clearInterval(saveTimer.current); }

  async function sendMessage(e?: FormEvent, retry = false) {
    e?.preventDefault(); if (!key || !vaultReady || busy || !connected || !selected) return;
    const userText = retry ? activeMessages.filter((m) => m.role === "user").at(-1)?.content ?? "" : draft.trim(); if (!userText) return;
    let conversation = active;
    if (!conversation) { const now = new Date().toISOString(); conversation = { id: id(), title: "New conversation", createdAt: now, updatedAt: now, messages: [] }; }
    const baseMessages = retry ? conversation.messages.filter((message) => !(message.role === "assistant" && message.error)) : conversation.messages;
    const userMessage = retry ? baseMessages.findLast((message) => message.role === "user")! : { id: id(), role: "user" as const, content: userText, createdAt: new Date().toISOString() };
    const assistant: ChatMessage = { id: id(), role: "assistant", content: "", createdAt: new Date().toISOString() };
    const messages = retry ? [...baseMessages, assistant] : [...baseMessages, userMessage, assistant];
    const updated: Conversation = { ...conversation, title: conversation.messages.length ? conversation.title : userText.slice(0, 44) + (userText.length > 44 ? "…" : ""), updatedAt: new Date().toISOString(), messages };
    const stored = { ...vaultRef.current, conversations: [updated, ...vaultRef.current.conversations.filter((item) => item.id !== updated.id)] };
    try { await persist(stored); } catch { setNotice("Your message could not be saved in the encrypted vault, so it was not sent."); return; }
    setActiveId(updated.id); setDraft(""); setBusy(true); const controller = new AbortController(); abortRef.current = controller;
    const context = [...(retry ? baseMessages : [...baseMessages, userMessage])].slice(-60).map(({ role, content }) => ({ role, content }));
    const memories = stored.memoryEnabled ? stored.memories.map((memory) => memory.text) : [];
    saveTimer.current = setInterval(() => { void writeVault(key, vaultRef.current).catch(() => undefined); }, 1800);
    try {
      const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json", Accept: "text/event-stream" }, body: JSON.stringify({ endpoint: settings.endpoint, model: selected, style: settings.style, responseLength: settings.responseLength, messages: context, memories }), signal: controller.signal });
      if (!response.ok) { const result = await response.json().catch(() => ({})) as { error?: string }; throw new Error(result.error ?? `The local model could not respond (${response.status}).`); }
      if (!response.body) throw new Error("The local model did not return a response stream.");
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let pending = "";
      while (true) { const { done, value } = await reader.read(); if (done) break; pending += decoder.decode(value, { stream: true }); let separator: number; while ((separator = pending.indexOf("\n\n")) >= 0) { const frame = pending.slice(0, separator); pending = pending.slice(separator + 2); const line = frame.split("\n").find((part) => part.startsWith("data: ")); if (!line) continue; const payload = JSON.parse(line.slice(6)) as { token?: string; error?: string; done?: boolean; safety?: string }; if (payload.error) throw new Error(payload.error); if (payload.safety) setNotice("MindSpace noticed that this could involve immediate safety. The reply includes options for contacting real-world support."); if (payload.token) { const current = vaultRef.current; const next = { ...current, conversations: current.conversations.map((item) => item.id === updated.id ? { ...item, messages: item.messages.map((msg) => msg.id === assistant.id ? { ...msg, content: msg.content + payload.token } : msg), updatedAt: new Date().toISOString() } : item) }; setVaultSafe(next); } } }
      await writeVault(key, vaultRef.current);
    } catch (error) {
      if ((error as Error).name === "AbortError") { await writeVault(key, vaultRef.current).catch(() => undefined); }
      else { const current = vaultRef.current; const next = { ...current, conversations: current.conversations.map((item) => item.id === updated.id ? { ...item, messages: item.messages.map((msg) => msg.id === assistant.id ? { ...msg, error: (error as Error).message } : msg) } : item) }; setVaultSafe(next); await writeVault(key, next).catch(() => undefined); }
    } finally { if (saveTimer.current) clearInterval(saveTimer.current); if (abortRef.current === controller) abortRef.current = null; setBusy(false); }
  }

  async function refreshModels() { setConnectionError(""); try { const list = await checkModels(settings.endpoint); setModels(list); setConnected(true); setSelected((current) => list.some((model) => model.name === current) ? current : list[0]?.name ?? ""); if (!list.length) setConnectionError("Ollama is running, but no completion models are installed. Install one in Ollama, then refresh here."); } catch (error) { setConnected(false); setModels([]); setConnectionError((error as Error).message); } }
  async function saveMemory(e: FormEvent) { e.preventDefault(); const text = memoryDraft.trim(); if (!text || text.length > 400) return; const now = new Date().toISOString(); const memories = editingMemory ? vaultRef.current.memories.map((memory) => memory.id === editingMemory ? { ...memory, text, updatedAt: now } : memory) : [{ id: id(), text, updatedAt: now }, ...vaultRef.current.memories]; try { await persist({ ...vaultRef.current, memories }); setMemoryDraft(""); setEditingMemory(""); } catch { setNotice("Could not save this memory in the encrypted vault."); } }
  async function deleteMemory(memory: Memory) { if (!window.confirm("Delete this saved memory?")) return; await persist({ ...vaultRef.current, memories: vaultRef.current.memories.filter((item) => item.id !== memory.id) }).catch(() => setNotice("Could not delete this memory.")); }
  async function clearMemories() { if (!window.confirm("Permanently clear all saved memories?")) return; await persist({ ...vaultRef.current, memories: [] }).catch(() => setNotice("Could not clear saved memories.")); }
  async function exportData() { const blob = new Blob([JSON.stringify(vaultRef.current, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `mindspace-export-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
  async function deleteEverything() { if (!window.confirm("Permanently delete all conversations, memories, personal entries, and local preferences from this browser? This cannot be undone.")) return; try { await permanentlyDeleteVault(); localStorage.removeItem(SETTINGS_KEY); localStorage.removeItem("mindspace.voice-settings.v1"); localStorage.removeItem("mindspace.face-preferences.v1"); lockVaultSession(); setKey(null); setVault(DEFAULT_VAULT); setVaultSafe(DEFAULT_VAULT); setVaultExists(false); setActiveId(""); setNotice("All local vault data and AI preferences were permanently deleted from this browser."); } catch (error) { setNotice((error as Error).message); } }
  function submitKey(e: KeyboardEvent<HTMLTextAreaElement>) { if ((e.ctrlKey || e.metaKey) && e.key === "Enter") { e.preventDefault(); void sendMessage(); } }

  if (loadingVault || vaultExists === null || (key && !vaultReady)) return <div className="vault-gate"><div className="vault-card"><Activity className="vault-icon"/><h2>Opening your private space…</h2><p>{key ? "Unlocking your encrypted conversations on this device." : "Your local encrypted vault is being checked."}</p></div></div>;
  if (!key) return <div className="vault-gate"><form className="vault-card" onSubmit={unlock}><div className="vault-icon"><LockKeyhole size={22}/></div><span className="eyebrow">Encrypted on this device</span><h2>{vaultExists ? "Unlock your conversations" : "Create your private vault"}</h2><p>{vaultExists ? "Enter your vault passphrase. It is never sent to the server." : "Choose a passphrase with at least 12 characters. It encrypts your conversations and memories; MindSpace cannot reset it."}</p><label className="field-label" htmlFor="vault-password">Vault passphrase</label><input id="vault-password" className="field-input" type="password" autoComplete="current-password" minLength={12} maxLength={256} required value={passphrase} onChange={(e) => setPassphrase(e.target.value)} placeholder="12 or more characters"/><p className="security-note">AES-256-GCM encryption · PBKDF2 key derivation · The vault key stays in this tab’s memory.</p>{unlockError && <div className="form-error" role="alert">{unlockError}</div>}<button className="button primary" disabled={loadingVault}>{loadingVault ? "Opening…" : vaultExists ? "Unlock vault" : "Create encrypted vault"}</button><Link className="smalltext muted" href="/settings">Ollama setup and privacy details</Link></form></div>;

  const filtered = vault.conversations.filter((conversation) => conversation.title.toLowerCase().includes(search.toLowerCase()) || conversation.messages.some((message) => message.content.toLowerCase().includes(search.toLowerCase())));
  return <div className="local-chat-layout">
    <aside className={`chat-history${showHistory ? " mobile-open" : ""}`}><div className="history-head"><div><span className="eyebrow" style={{ padding: 0 }}>YOUR CONVERSATIONS</span><div className="connection-chip"><i className={`dot${connected ? " teal" : ""}`}/>{connected ? `${models.length} local model${models.length === 1 ? "" : "s"}` : "Ollama disconnected"}</div></div><button className="icon-btn" title="New conversation (Ctrl+N)" onClick={() => void newConversation()}><Plus size={17}/></button></div>
      <div className="history-tools"><button className={`icon-btn small ${searchOpen ? "active" : ""}`} onClick={() => { setSearchOpen(!searchOpen); setSearch(""); }} title="Search conversations"><Search size={14}/></button><button className="icon-btn small" title="Export conversations and memories" onClick={() => void exportData()}><Download size={14}/></button></div>{searchOpen && <input className="field-input history-search" value={search} autoFocus onChange={(e) => setSearch(e.target.value)} placeholder="Search conversations…"/>}
      <div className="history-list">{filtered.map((conversation) => <div key={conversation.id} role="button" tabIndex={0} className={`history-item${conversation.id === activeId ? " selected" : ""}`} onClick={() => { setActiveId(conversation.id); setShowHistory(false); }} onKeyDown={(e) => { if (e.key === "Enter") { setActiveId(conversation.id); setShowHistory(false); } }}><div className="history-line"><MessageCircle size={14}/><span>{conversation.title}</span></div><div className="history-meta">{conversation.messages.length ? `${conversation.messages.length} messages · ` : ""}{localTime(conversation.updatedAt)}<div className="row"><button aria-label="Rename conversation" title="Rename" onClick={(e) => { e.stopPropagation(); void renameConversation(conversation); }}><Edit2 size={12}/></button><button aria-label="Delete conversation" title="Delete" onClick={(e) => { e.stopPropagation(); void removeConversation(conversation); }}><Trash2 size={12}/></button></div></div></div>)}{filtered.length === 0 && <div className="history-empty">{search ? "No conversations match." : "Your conversations will appear here."}</div>}</div>
      <div className="history-bottom"><button onClick={() => setMemoryOpen(!memoryOpen)}><LockKeyhole size={15}/> Memories <span>{vault.memories.length}</span></button><button onClick={() => void deleteEverything()}><Trash2 size={14}/> Delete all local data</button></div>
    </aside>
    <section className="chat-main"><header className="chat-toolbar"><div className="chat-toolbar-title"><span className="eyebrow" style={{ padding: 0 }}>{active?.title ?? "A space to talk"}</span><div className="status"><i className={`dot${connected ? " teal" : ""}`}/>{connected ? "Ollama connected" : "Not connected"}</div></div><div className="row"><button className="icon-btn history-toggle" onClick={() => setShowHistory(!showHistory)} title="Open conversation history" aria-label="Open conversation history"><List size={15}/></button><button className="icon-btn" onClick={() => void newConversation()} title="New conversation"><Plus size={15}/></button><button className="icon-btn" onClick={() => setMemoryOpen(!memoryOpen)} title="Saved memories"><LockKeyhole size={15}/></button><button className="icon-btn export-toggle" onClick={() => void exportData()} title="Export conversations and memories"><Download size={15}/></button><select aria-label="Choose local model" disabled={!connected || !models.length} value={selected} onChange={(e) => { const model = e.target.value; setSelected(model); const updated = { ...settings, model }; setSettings(updated); localStorage.setItem(SETTINGS_KEY, JSON.stringify(updated)); }} className="model-select">{models.length ? models.map((model) => <option value={model.name} key={model.name}>{model.name}</option>) : <option>{connected ? "No models installed" : "Ollama unavailable"}</option>}</select><button className="icon-btn" onClick={() => void refreshModels()} title="Check Ollama connection"><RefreshCw size={15}/></button>{active && <button className="icon-btn" title="Clear this conversation" onClick={() => void clearConversation(active)}><Trash2 size={15}/></button>}<Link className="icon-btn settings-toggle" href="/settings" title="AI settings"><Settings2 size={15}/></Link></div></header>
      {!connected && <div className="connection-alert" role="status"><Activity size={17}/><div><strong>Ollama isn’t responding</strong><span>{connectionError || "Start the Ollama app, then refresh this connection."} · Check <a href="https://docs.ollama.com/" target="_blank" rel="noreferrer">Ollama setup</a>. No messages are sent while disconnected.</span></div><button className="button small" onClick={() => void refreshModels()}>Retry connection</button></div>}
      {connected && !models.length && <div className="connection-alert" role="status"><Activity size={17}/><div><strong>No installed chat models</strong><span>{connectionError || "Install a model in the Ollama app or with its CLI. MindSpace will never download one for you."}</span></div></div>}
      <div className="chat-scroll" ref={scrollRef} aria-live="polite">{!activeMessages.length ? <div className="chat-welcome"><div className="chat-orb"><MessageCircle size={25}/></div><h2>{active ? "Whenever you’re ready" : "A space to talk"}</h2><p>Talk about the big things, the small things, or just whatever’s on your mind. I’ll listen and follow your lead.</p><span className="privacy-caption"><LockKeyhole size={13}/> Your messages are encrypted and saved on this device.</span>{!connected && <div className="setup-steps"><strong>To get started</strong><ol><li>Install and open Ollama on this computer.</li><li>Download a local model using Ollama’s app or CLI.</li><li>Refresh the connection above and choose your model.</li></ol><Link href="/settings">Configure local connection <ArrowRight size={14}/></Link></div>}</div> : activeMessages.map((message) => <article className={`message-row ${message.role}`} key={message.id}><div className={`message-avatar ${message.role}`}>{message.role === "assistant" ? <span>m</span> : "you"}</div><div className="message-body"><div className="message-meta"><strong>{message.role === "assistant" ? "mindspace" : "you"}</strong><time dateTime={message.createdAt}>{localTime(message.createdAt)}</time></div>{message.role === "assistant" && message.error ? <div className="message-error" role="alert"><span>{message.error}</span><button className="button small" onClick={() => void sendMessage(undefined, true)}><RefreshCw size={13}/> Retry</button></div> : message.role === "assistant" ? <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{message.content || (busy && message.id === activeMessages.at(-1)?.id ? "…" : "")}</ReactMarkdown></div> : <div className="user-message">{message.content}</div>}{message.role === "assistant" && message.content && <div className="message-actions"><button title="Copy response" aria-label="Copy response" onClick={() => { void navigator.clipboard.writeText(message.content); setNotice("Response copied to clipboard."); }}><Clipboard size={13}/> Copy</button>{message.id === activeMessages.at(-1)?.id && !busy && <button onClick={() => void sendMessage(undefined, true)}><RefreshCw size={13}/> Retry</button>}</div>}</div></article>)}</div>
      {notice && <div className="chat-notice" role="status">{notice}<button aria-label="Dismiss" onClick={() => setNotice("")}><X size={14}/></button></div>}
      <div className="composer-wrap"><form className="composer" onSubmit={(e) => void sendMessage(e)}><textarea ref={inputRef} value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={submitKey} maxLength={8000} rows={1} placeholder={connected ? "Share what’s on your mind…" : "Start Ollama to begin a conversation"} aria-label="Your message" disabled={!connected || busy} /><button className={`send-button${busy ? " stopping" : ""}`} type={busy ? "button" : "submit"} aria-label={busy ? "Stop generation" : "Send message"} disabled={!busy && (!connected || !selected || !draft.trim())} onClick={busy ? stop : undefined}>{busy ? <Pause size={16}/> : <Send size={16}/>}</button></form><div className="composer-foot"><span>Return for a new line · Ctrl/⌘ + Enter to send · Ctrl/⌘ + N for new chat</span><span><LockKeyhole size={12}/> Local and encrypted</span></div></div>
    </section>
    {memoryOpen && <aside className="memory-panel"><div className="memory-head"><div><LockKeyhole size={16}/><strong>Your memories</strong></div><button className="icon-btn" onClick={() => setMemoryOpen(false)} aria-label="Close memories"><X size={15}/></button></div><p className="smalltext muted">Only details you add here are remembered between conversations. Nothing is saved automatically.</p><label className="switchrow memory-toggle"><span><strong>Use memories in chat</strong><small>Included only with your local model prompts</small></span><button className={`switch${vault.memoryEnabled ? " on" : ""}`} role="switch" aria-checked={vault.memoryEnabled} aria-label="Use saved memories in conversation" onClick={() => void persist({ ...vaultRef.current, memoryEnabled: !vaultRef.current.memoryEnabled })}/></label><form onSubmit={(e) => void saveMemory(e)}><textarea className="field-input memory-input" rows={3} maxLength={400} value={memoryDraft} onChange={(e) => setMemoryDraft(e.target.value)} placeholder="A preference or detail you want MindSpace to remember…"/><div className="row" style={{ justifyContent: "space-between", marginTop: 7 }}><span className="smalltext muted">{memoryDraft.length}/400</span><button className="button primary small" disabled={!memoryDraft.trim()}>{editingMemory ? "Save change" : "Add memory"}</button></div></form><div className="memory-list">{vault.memories.map((memory) => <div className="memory-item" key={memory.id}><p>{memory.text}</p><div className="row"><button onClick={() => { setMemoryDraft(memory.text); setEditingMemory(memory.id); }}><Edit2 size={12}/> Edit</button><button onClick={() => void deleteMemory(memory)}><Trash2 size={12}/> Delete</button></div></div>)}{!vault.memories.length && <div className="history-empty">No saved memories. Add only what you choose to keep.</div>}</div>{vault.memories.length > 0 && <button className="button small" style={{ marginTop: 12 }} onClick={() => void clearMemories()}><Trash2 size={13}/> Clear all memories</button>}<div className="memory-warning"><ShieldAlert size={15}/> Memories are encrypted locally and sent only to your selected Ollama model when memory is enabled. Treat them as context, not private authentication secrets.</div></aside>}
  </div>;
}

export function AssistantSettings() {
  const [settings, setSettings] = useState<LocalSettings>(DEFAULT_SETTINGS); const [endpointDraft, setEndpointDraft] = useState(DEFAULT_SETTINGS.endpoint); const [models, setModels] = useState<Model[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [connected, setConnected] = useState(false);
  useEffect(() => { const saved = readSettings(); setSettings(saved); setEndpointDraft(saved.endpoint); void inspect(saved.endpoint, saved.model); }, []);
  async function inspect(endpoint: string, selected: string) { setBusy(true); setError(""); try { const list = await checkModels(endpoint); setModels(list); setConnected(true); const model = list.some((item) => item.name === selected) ? selected : list[0]?.name ?? ""; const next = { ...readSettings(), endpoint, model }; setSettings(next); localStorage.setItem(SETTINGS_KEY, JSON.stringify(next)); if (!list.length) setError("Ollama is running, but no completion models are installed."); } catch (err) { setConnected(false); setModels([]); setError((err as Error).message); } finally { setBusy(false); } }
  function update(patch: Partial<LocalSettings>) { const next = { ...settings, ...patch }; setSettings(next); localStorage.setItem(SETTINGS_KEY, JSON.stringify(next)); }
  return <div className="ai-settings-page"><div className="card"><div className="card-head"><div><div className="card-title"><Activity size={17}/> Ollama connection</div><p className="muted smalltext" style={{ margin: "6px 0 0" }}>MindSpace talks only to your local Ollama service.</p></div><span className="status"><i className={`dot${connected ? " teal" : ""}`}/>{connected ? "Connected" : "Unavailable"}</span></div><label className="field-label" htmlFor="ollama-endpoint">Local endpoint</label><div className="row endpoint-row"><input id="ollama-endpoint" className="field-input" value={endpointDraft} maxLength={120} onChange={(e) => setEndpointDraft(e.target.value)} placeholder="http://127.0.0.1:11434"/><button className="button primary" disabled={busy} onClick={() => void inspect(endpointDraft, settings.model)}>{busy ? "Checking…" : "Check connection"}</button></div><p className="smalltext muted">Only HTTP loopback addresses such as 127.0.0.1 or ::1 are accepted. No internet or other network hosts can be configured.</p>{error && <div className="form-error" role="status">{error}</div>}{connected && <div className="settings-row"><div><strong>Chat model</strong><p className="smalltext muted">Installed models only. MindSpace never downloads models.</p></div><select className="model-select" value={settings.model} onChange={(e) => update({ model: e.target.value })}>{models.length ? models.map((model) => <option key={model.name} value={model.name}>{model.name} · {fmtSize(model.size)}</option>) : <option value="">No installed models</option>}</select></div>}</div>
    <div className="card"><div className="card-title"><MessageCircle size={17}/> Conversation style</div><p className="smalltext muted">Choose how your local companion talks with you.</p><div className="style-grid">{([["friendly","Friendly","Warm and easy to talk to"],["calm","Calm","Gentle and unhurried"],["thoughtful","Thoughtful","Curious and reflective"],["encouraging","Encouraging","Supportive without pressure"]] as const).map(([value,label,copy]) => <button className={`style-option${settings.style === value ? " selected" : ""}`} key={value} onClick={() => update({ style: value })}><span>{label}{settings.style === value && <Check size={14}/>}</span><small>{copy}</small></button>)}</div></div>
    <div className="card"><div className="card-title"><LockKeyhole size={17}/> Storage & safety</div><div className="settings-row"><div><strong>Where conversation data lives</strong><p className="smalltext muted">The app server relays messages to Ollama at the loopback endpoint. Conversation and memory records are encrypted in IndexedDB in this browser; they are decrypted only in this tab after you unlock your vault.</p></div></div><div className="settings-row"><div><strong>Encryption limitations</strong><p className="smalltext muted">AES-GCM with a passphrase-derived key helps protect a copied storage database. Browser extensions, malware, someone using an unlocked session, weak passphrases, or browser backups can still expose data. The passphrase is never stored and cannot be reset.</p></div></div><div className="settings-row"><div><strong>Wellness companion, not clinical care</strong><p className="smalltext muted">MindSpace does not diagnose or contact emergency services. For immediate danger, contact a trusted person or your local emergency service.</p></div></div><Link href="/chat" className="button small"><ArrowLeft size={13}/> Back to conversation</Link></div>
  </div>;
}
